### ISSUE TITLE
Form options overriding

### ISSUE THREAD

**Issue by vladislavs1321** [netgen/NetgenEzFormsBundle#35]
Hey guys, will be cool to have possibility to override existing form items options, like disable label rendering, placeholders, select configurations.

**Comment by MarioBlazek** [comment]
@vladislavs1321 can you please specify more details about this one ? Thanks.

**Comment by vladislavs1321** [comment]
@MarioBlazek  for example typical user registration form, with ez User object and some additional inputs like address, phone (text types), and by our design for example we don't need to show labels, but need to create placeholders. Of course, we can try to manage this with form theme, but will be so good to have possibility to have a possibility to set this from form object

**Comment by MarioBlazek** [comment]
Did you try to add placeholders like this @vladislavs1321 ?

In Controller:
```php
/** @var FormBuilderInterface $formBuilder */
$formBuilder = $this->something();

$field = $formBuilder->get('email');
$options = $field->getOptions();
$type = $field->getType()->getName();
$options['attr']['placeholder'] = "My placeholder";

$formBuilder->add('email', $type, $options);
```

In template:
```jinja
<div class="form-group">
    <div class="control-label">
        {{ form_label( form.email ) }}:
    </div>
    {{ form_widget( form.email, {'attr': {'class': 'form-control', 'placeholder': 'My placeholder'} } ) }}
    {{ form_errors(form.email)}}
</div>
```

**Comment by MarioBlazek** [comment]
@vladislavs1321 did this helped you ?

**Comment by vladislavs1321** [comment]
@MarioBlazek  a little bit, so i decide to override Form\Type\FieldType\UserCreateType to put placeholders in this form type and bring not ideal solution in my twig 
```{% for form_child in form.children %}
                            {% if form_child.vars.name != 'user_account' %}
                                {{ form_row( form_child, { attr: { class: 'form-control', placeholder: form_child.vars.label } } ) }}
                            {% else %}
                                {{ form_row( form_child, { attr: { class: 'form-control' } } ) }}
                            {% endif %}
                        {% endfor %}

to avoid using hardcoded FormBuilder children elements names
