### ISSUE TITLE
"Selection" ist nor wotking properly

### ISSUE THREAD

**Issue by amirkoklan** [netgen/NetgenEzFormsBundle#37]
I have a "ezselection" field type in my form with three options. 1,2,3

when I select 1 in frontend and submit the form, in ez backoffice I see 2 is selected and when I select 2 in my form in frontend in ez backoffice I see 3 has been selected.

Info:
ezsystems/ezpublish-kernel
dev-master dev (19.04.17, 12:36, 079a2)

netgen/ez-forms-bundle
1.3.2 (15.01.17, 14:53, 87ed3)

netgen/information-collection-bundle
v1.0.2 (18.04.17, 16:41, e4823)

**Comment by MarioBlazek** [comment]
@amirkoklan thanks for submitting issue, we will check this asap.

**Comment by MarioBlazek** [comment]
@amirkoklan I cannot reproduce problem that you described here. Can you check in `ezcontentobject_attribute` table which values are stored there ?

**Comment by MarioBlazek** [comment]
@amirkoklan any update on this ?

**Comment by amirkoklan** [comment]
as I wrote you in slack, this was an error in platformUI and not your extension and should have been solved with this PR https://github.com/ezsystems/PlatformUIBundle/pull/853

**Comment by MarioBlazek** [comment]
Thanks for info.
